name = "aiken-lang/market-contracts-beta"
version = "0.0.0"
compiler = "v1.1.9"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/market-contracts-beta'"

[repository]
user = "aiken-lang"
project = "market-contracts-beta"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"
